Parameters:	
x : array_like

1-D input array.

N : int, optional

Number of columns in the output. If N is not specified, a square array is returned (N = len(x)).

increasing : bool, optional

Order of the powers of the columns. If True, the powers increase from left to right, if False (the default) they are reversed.

Returns:	
out : ndarray

Vandermonde matrix. If increasing is False, the first column is x^(N-1), the second x^(N-2) and so forth. If increasing is True, the columns are x^0, x^1, ..., x^(N-1).

In [1]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = int(input("Enter power of input vector: "))
np.vander(x, N,increasing=True)

Enter power of input vector: 3


array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [2]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = int(input("Enter power of input vector: "))
np.vander(x, N,increasing=False)

Enter power of input vector: 3


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [3]:
import numpy as np
x = np.array([1, 2, 3, 5])
np.vander(x,increasing=False)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])